title: Mo Alserr - Technical blog
email: mo.alserr@outlook.com
description: >- 
  Big data architect, python data scientist, machine learning expert but Java guru from beginning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: malserr
github_username:  momomagic

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
theme: jekyll-theme-architect
